In [ ]:
# ==========================
# Python DA Assignment 1
# NumPy and Pandas
# ==========================

import numpy as np
import pandas as pd

# --------------------------
# NUMPY ARRAY OPERATIONS
# --------------------------

# 1. Create 1D NumPy Array
temperatures_w1 = np.array([22.5, 25.3, 20.8, 23.4, 26.1, 24.8, 21.9])

print("Week 1 Temperatures:")
print(temperatures_w1)

# 2. Inspection and Properties
print("\nShape:", temperatures_w1.shape)
print("Data Type:", temperatures_w1.dtype)
print("Number of Elements:", temperatures_w1.size)

# 3. Array Operations
fahrenheit = (temperatures_w1 * 9/5) + 32

print("\nTemperatures in Fahrenheit:")
print(fahrenheit)

print("\nMaximum Temperature:", temperatures_w1.max())
print("Minimum Temperature:", temperatures_w1.min())
print("Mean Temperature:", temperatures_w1.mean())

# 4. Array Slicing and Indexing
print("\nFirst Three Days:")
print(temperatures_w1[:3])

print("\nWeekend Temperatures:")
print(temperatures_w1[-2:])

print("\nMiddle Three Days:")
print(temperatures_w1[2:5])

# 5. Create 2D Array
temperatures = np.array([
    [22.5, 25.3, 20.8, 23.4, 26.1, 24.8, 21.9],
    [19.2, 22.5, 21.3, 24.0, 23.5, 22.8, 20.1]
])

print("\n2D Array:")
print(temperatures)

# 6. Inspect and Slice 2D Array
print("\nShape:", temperatures.shape)
print("Data Type:", temperatures.dtype)
print("Total Elements:", temperatures.size)

print("\nWeek 1:")
print(temperatures[0])

print("\nWeek 2:")
print(temperatures[1])

print("\nWeekend Temperatures:")
print(temperatures[:, -2:])

# --------------------------
# PANDAS SERIES
# --------------------------

marks = pd.Series(
    [95, 92, 89, 85, 80],
    index=["Rank1", "Rank2", "Rank3", "Rank4", "Rank5"]
)

print("\nMarks Series:")
print(marks)

# Indexing
print("\n1st Rank Mark:")
print(marks.iloc[0])

print("\nTop 3 Ranks:")
print(marks.loc[["Rank1", "Rank2", "Rank3"]])

print("\n3rd Rank:")
print(marks.iloc[2])

print("\nMarks Greater Than 90:")
print(marks[marks > 90])

# Manipulation
marks["Rank1"] = 100

marks = marks.drop("Rank5")

cgpa = marks / 10

print("\nUpdated Marks:")
print(marks)

print("\nCGPA:")
print(cgpa)

# --------------------------
# PANDAS DATAFRAME
# --------------------------

transactions = pd.DataFrame({
    "TransactionID":[101,102,103,104,105,106,107,108,109,110],
    "ProductCategory":[
        "Electronics","Clothing","Electronics","Furniture",
        "Clothing","Electronics","Furniture","Clothing",
        "Furniture","Electronics"
    ],
    "Region":[
        "North","South","North","East",
        "West","North","East","West",
        "South","North"
    ],
    "Amount":[200,150,300,450,200,250,300,180,350,400]
})

print("\nTransactions DataFrame:")
print(transactions)

# Data Exploration
print("\nHead:")
print(transactions.head())

print("\nTail:")
print(transactions.tail())

print("\nShape:")
print(transactions.shape)

print("\nColumns:")
print(transactions.columns)

print("\nData Types:")
print(transactions.dtypes)

print("\nProductCategory and Amount:")
print(transactions[["ProductCategory","Amount"]])

print("\nLast 3 Columns:")
print(transactions.iloc[:, -3:])

print("\nNorth Region and Amount > 200:")
print(transactions[
    (transactions["Region"]=="North") &
    (transactions["Amount"]>200)
])

print("\nProduct Category Counts:")
print(transactions["ProductCategory"].value_counts())

print("\nUnique Regions:")
print(transactions["Region"].unique())

print("\nMean Amount by Region:")
print(transactions.groupby("Region")["Amount"].mean())

# DataFrame Manipulation

transactions.loc[
    transactions["TransactionID"]==102,
    "Amount"
] = 165

transactions["Discount"] = transactions["Amount"] * 0.10

transactions = transactions[
    transactions["TransactionID"] != 109
]

transactions = transactions.drop(columns=["Discount"])

print("\nFinal DataFrame:")
print(transactions)

Week 1 Temperatures:
[22.5 25.3 20.8 23.4 26.1 24.8 21.9]

Shape: (7,)
Data Type: float64
Number of Elements: 7

Temperatures in Fahrenheit:
[72.5  77.54 69.44 74.12 78.98 76.64 71.42]

Maximum Temperature: 26.1
Minimum Temperature: 20.8
Mean Temperature: 23.542857142857144

First Three Days:
[22.5 25.3 20.8]

Weekend Temperatures:
[24.8 21.9]

Middle Three Days:
[20.8 23.4 26.1]

2D Array:
[[22.5 25.3 20.8 23.4 26.1 24.8 21.9]
 [19.2 22.5 21.3 24.  23.5 22.8 20.1]]

Shape: (2, 7)
Data Type: float64
Total Elements: 14

Week 1:
[22.5 25.3 20.8 23.4 26.1 24.8 21.9]

Week 2:
[19.2 22.5 21.3 24.  23.5 22.8 20.1]

Weekend Temperatures:
[[24.8 21.9]
 [22.8 20.1]]

Marks Series:
Rank1    95
Rank2    92
Rank3    89
Rank4    85
Rank5    80
dtype: int64

1st Rank Mark:
95

Top 3 Ranks:
Rank1    95
Rank2    92
Rank3    89
dtype: int64

3rd Rank:
89

Marks Greater Than 90:
Rank1    95
Rank2    92
dtype: int64

Updated Marks:
Rank1    100
Rank2     92
Rank3     89
Rank4     85
dtype: int64

CGPA:
R